version: '3.4'

services:
  wastenot:
    image: wastenot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      APP_PORT: 3000
      DB_PORT: 27017
    ports:
      - 3000:3000
  mongodb:
    image: mongo:6.0
